import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";

export const dynamic = 'force-dynamic';
export const maxDuration = 30;

// Updated list of Piped API instances (as of Dec 2024)
const PIPED_INSTANCES = [
  "https://pipedapi.tokhmi.xyz",
  "https://pipedapi.moomoo.me",
  "https://pipedapi.syncpundit.io",
  "https://api-piped.mha.fi",
  "https://pipedapi.in.projectsegfau.lt",
  "https://pipedapi.colinslegacy.com",
  "https://pipedapi.us.projectsegfau.lt",
  "https://pipedapi.phoenixthrush.com",
];

interface SubtitleSegment {
  text: string;
  start: number;
  duration: number;
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/&#(\d+);/g, (_, num) => String.fromCharCode(parseInt(num, 10)));
}

function parseVttTranscript(vttText: string): SubtitleSegment[] {
  const segments: SubtitleSegment[] = [];
  const cues = vttText.split(/\n\n+/);
  
  for (const cue of cues) {
    const timestampMatch = cue.match(/(\d{2}):(\d{2}):(\d{2})\.(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})\.(\d{3})/);
    if (timestampMatch) {
      const startMs = (parseInt(timestampMatch[1]) * 3600 + parseInt(timestampMatch[2]) * 60 + parseInt(timestampMatch[3])) * 1000 + parseInt(timestampMatch[4]);
      const endMs = (parseInt(timestampMatch[5]) * 3600 + parseInt(timestampMatch[6]) * 60 + parseInt(timestampMatch[7])) * 1000 + parseInt(timestampMatch[8]);
      
      const lines = cue.split('\n');
      const textLines = lines.slice(lines.findIndex(l => l.includes('-->')) + 1);
      const text = decodeHtmlEntities(textLines.join(' ').replace(/<[^>]*>/g, '').trim());
      
      if (text) {
        segments.push({
          text,
          start: startMs,
          duration: endMs - startMs
        });
      }
    }
  }
  
  return segments;
}

function parseXmlTranscript(xmlText: string): SubtitleSegment[] {
  const segments: SubtitleSegment[] = [];
  const matches = [...xmlText.matchAll(/<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g)];
  
  matches.forEach(m => {
    const text = decodeHtmlEntities(m[3].replace(/<[^>]*>/g, '').trim());
    if (text) {
      segments.push({
        text,
        start: parseFloat(m[1]) * 1000,
        duration: parseFloat(m[2]) * 1000
      });
    }
  });
  
  return segments;
}

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const videoId = searchParams.get("videoId");

  if (!videoId) {
    return NextResponse.json({ error: "Missing videoId" }, { status: 400 });
  }

  console.log(`[Piped Proxy] Fetching for ${videoId}`);

  for (const instance of PIPED_INSTANCES) {
    try {
      console.log(`[Piped Proxy] Trying ${instance}`);
      
      const response = await fetch(`${instance}/streams/${videoId}`, {
        headers: {
          'Accept': 'application/json',
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        },
        signal: AbortSignal.timeout(8000)
      });
      
      if (!response.ok) {
        console.log(`[Piped Proxy] ${instance} returned ${response.status}`);
        continue;
      }
      
      const data = await response.json();
      const subtitles = data.subtitles || [];
      
      console.log(`[Piped Proxy] Found ${subtitles.length} subtitle tracks`);
      
      if (subtitles.length === 0) {
        console.log(`[Piped Proxy] No subtitles at ${instance}`);
        continue;
      }
      
      // Find English subtitles (auto-generated or manual)
      const englishSub = 
        subtitles.find((s: any) => s.code === 'en' && !s.autoGenerated) ||
        subtitles.find((s: any) => s.code === 'en') ||
        subtitles.find((s: any) => s.code?.startsWith('en')) ||
        subtitles.find((s: any) => s.name?.toLowerCase().includes('english')) ||
        subtitles.find((s: any) => s.autoGenerated); // Any auto-generated as fallback
      
      if (!englishSub?.url) {
        console.log(`[Piped Proxy] No suitable subtitle found`);
        console.log(`[Piped Proxy] Available: ${subtitles.map((s: any) => `${s.code}:${s.name}`).join(', ')}`);
        continue;
      }
      
      console.log(`[Piped Proxy] Using: ${englishSub.name || englishSub.code}`);
      
      const subResponse = await fetch(englishSub.url, {
        headers: {
          'Accept': '*/*',
          'User-Agent': 'Mozilla/5.0',
        },
        signal: AbortSignal.timeout(8000)
      });
      
      if (!subResponse.ok) {
        console.log(`[Piped Proxy] Subtitle fetch returned ${subResponse.status}`);
        continue;
      }
      
      const subText = await subResponse.text();
      console.log(`[Piped Proxy] Got subtitle, length: ${subText.length}`);
      
      if (subText.length < 50) continue;
      
      // Parse based on format
      let segments: SubtitleSegment[] = [];
      
      if (subText.includes('WEBVTT') || subText.includes('-->')) {
        segments = parseVttTranscript(subText);
      } else if (subText.includes('<text')) {
        segments = parseXmlTranscript(subText);
      }
      
      if (segments.length > 0) {
        console.log(`[Piped Proxy] SUCCESS: ${segments.length} segments`);
        return NextResponse.json({ segments });
      }
      
    } catch (e: any) {
      console.log(`[Piped Proxy] ${instance} failed: ${e.message}`);
    }
  }

  console.log(`[Piped Proxy] All instances failed`);
  return NextResponse.json({ 
    error: "No subtitles found",
    code: "NO_TRANSCRIPT" 
  }, { status: 404 });
}
