import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";

export const dynamic = 'force-dynamic';

// Piped API instances to try
const PIPED_INSTANCES = [
  "https://pipedapi.kavin.rocks",
  "https://pipedapi.adminforge.de",
  "https://api.piped.yt",
  "https://pipedapi.r4fo.com",
  "https://pipedapi.leptons.xyz",
];

interface SubtitleSegment {
  text: string;
  start: number;
  duration: number;
}

// Helper to decode HTML entities
function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/&#(\d+);/g, (_, num) => String.fromCharCode(parseInt(num, 10)));
}

// Parse VTT format
function parseVttTranscript(vttText: string): SubtitleSegment[] {
  const segments: SubtitleSegment[] = [];
  const cues = vttText.split(/\n\n+/);
  
  for (const cue of cues) {
    // Match timestamp: 00:00:00.000 --> 00:00:05.000
    const timestampMatch = cue.match(/(\d{2}):(\d{2}):(\d{2})\.(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})\.(\d{3})/);
    if (timestampMatch) {
      const startMs = (parseInt(timestampMatch[1]) * 3600 + parseInt(timestampMatch[2]) * 60 + parseInt(timestampMatch[3])) * 1000 + parseInt(timestampMatch[4]);
      const endMs = (parseInt(timestampMatch[5]) * 3600 + parseInt(timestampMatch[6]) * 60 + parseInt(timestampMatch[7])) * 1000 + parseInt(timestampMatch[8]);
      
      const lines = cue.split('\n');
      const textLines = lines.slice(lines.findIndex(l => l.includes('-->')) + 1);
      const text = decodeHtmlEntities(textLines.join(' ').replace(/<[^>]*>/g, '').trim());
      
      if (text) {
        segments.push({
          text,
          start: startMs,
          duration: endMs - startMs
        });
      }
    }
  }
  
  return segments;
}

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const videoId = searchParams.get("videoId");

  if (!videoId) {
    return NextResponse.json({ error: "Missing videoId" }, { status: 400 });
  }

  console.log(`[Piped Proxy] Fetching subtitles for ${videoId}`);

  for (const instance of PIPED_INSTANCES) {
    try {
      console.log(`[Piped Proxy] Trying ${instance}`);
      
      // Get video info which includes subtitles
      const response = await fetch(`${instance}/streams/${videoId}`, {
        headers: {
          'Accept': 'application/json',
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        },
        signal: AbortSignal.timeout(10000)
      });
      
      if (!response.ok) {
        console.log(`[Piped Proxy] ${instance} returned ${response.status}`);
        continue;
      }
      
      const data = await response.json();
      
      // Find English subtitles
      const subtitles = data.subtitles || [];
      console.log(`[Piped Proxy] Found ${subtitles.length} subtitle tracks`);
      
      const englishSub = subtitles.find((s: any) => 
        s.code === 'en' || 
        s.code?.startsWith('en') ||
        s.name?.toLowerCase().includes('english') ||
        s.autoGenerated === true
      );
      
      if (!englishSub?.url) {
        console.log(`[Piped Proxy] No English subtitles found at ${instance}`);
        // Log available subtitles for debugging
        console.log(`[Piped Proxy] Available:`, subtitles.map((s: any) => `${s.code}: ${s.name}`).join(', '));
        continue;
      }
      
      console.log(`[Piped Proxy] Found subtitle: ${englishSub.name || englishSub.code}, URL: ${englishSub.url}`);
      
      // Fetch the subtitle content
      const subResponse = await fetch(englishSub.url, {
        headers: {
          'Accept': '*/*',
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        },
        signal: AbortSignal.timeout(10000)
      });
      
      if (!subResponse.ok) {
        console.log(`[Piped Proxy] Subtitle fetch returned ${subResponse.status}`);
        continue;
      }
      
      const subText = await subResponse.text();
      console.log(`[Piped Proxy] Got subtitle text, length: ${subText.length}`);
      
      if (subText.length < 100) {
        console.log(`[Piped Proxy] Subtitle text too short, skipping`);
        continue;
      }
      
      // Parse VTT format
      const segments = parseVttTranscript(subText);
      
      if (segments.length > 0) {
        console.log(`[Piped Proxy] Successfully parsed ${segments.length} segments`);
        return NextResponse.json({ segments });
      }
      
      console.log(`[Piped Proxy] Failed to parse subtitles`);
      
    } catch (e: any) {
      console.log(`[Piped Proxy] ${instance} failed:`, e.message);
    }
  }

  console.log(`[Piped Proxy] All instances failed for ${videoId}`);
  return NextResponse.json({ 
    error: "No subtitles found",
    code: "NO_TRANSCRIPT" 
  }, { status: 404 });
}

